name: YAFD CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd 5_Source_Code/backend
        pip install -r requirements.txt

    - name: Run Flask app test (basic import check)
      run: |
        cd 5_Source_Code/backend
        python -c "import app"

    - name: Build Docker image
      run: |
        cd 5_Source_Code/backend
        docker build -t yafd-backend .
