name: YAFD CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd 5_Source_Code/backend
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd 5_Source_Code/backend
        pytest tests/

    - name: Build Docker image
      run: |
        cd 5_Source_Code/backend
        docker build -t yafd-backend .
